#!/bin/sh

SCRIPT=fb-login2
LOGFILE=/var/log/busy4me.log

logline() {
    while IFS= read -r line; do
        echo "$(date +%F' '%T) $USER $SCRIPT - $line" | tee -a $LOGFILE 
    done
}

# move mouse away...
echo "move mouse away...." | logline
xdotool mousemove 0 0
# update date before login....
echo "update date before login...." | logline
ntpdate -s time.nist.gov | logline

kds=50 # Key Delay Short [miliseconds]
kd=250 # Key Delay [miliseconds]
kdl=500 # Key Delay Long [miliseconds]
tos=1 # Time Out Short zenity messages time out [seconds] 
to=1 # Time Out zenity messages time out [seconds] 
tol=5 # Time Out Long zenity messages time out [seconds] 
login=fblogin@email.com
password=fbpassword
login_url=http://m.facebook.com

shake () {
xdotool key --delay 200 Page_Down End Page_Up Home
}

echo "is it mobile login page?"

SPOT01="facebook" # spot 01
SPOT01url="http://facebook.com" # url 01
#xdotool search --sync --onlyvisible --name "$SPOT01" windowunmap windowmap | logline
xdotool search --sync --onlyvisible --name "$SPOT01" windowactivate | logline
echo "...select and copy"
xdotool key --delay 200 Ctrl+a Ctrl+c | logline
echo "...all selected"
echo "...unselect"
xdotool key --delay 200 Ctrl+Shift+a | logline
clip=$( xclip -out -selection clipboard )
echo "...zenity"
zenity --info --title="clipboard" --text="$clip" --timeout $to
echo "...END"

echo "is it english?"
echo "is it logged?"
mark01='Create an account' #special sign from the MAIN LOGIN site
mark02='Create New Account' #special sign from the MAIN LOGIN site
case "$clip" in 
    *$mark01*) 
	echo "Main login page...Not logged"
	zenity --info --title="clipboard" --text="Mine login page...not logged..." --timeout $to
  ;;
    *$mark02*) 
	echo "Mobile login page...Not logged"
	zenity --info --title="clipboard" --text="Mobile login page...not logged..." --timeout $to
  ;;
    *)
	zenity --question --title="Status" --text="What is the page status?" --timeout $to
  ;;
esac

# open mobile page...
xdotool search --sync --onlyvisible --name "$SPOT01" windowactivate | logline
xdotool key --delay 200 Ctrl+l | logline
xdotool type $login_url
xdotool key --delay 200 Return


empty01=""
mark02='Forgotten'
mark03='Help Centre'
mark04='Facebook'
mark05='https://m.facebook.com'
mark06='Cookies Policy'
mark07="What's on your mind"
mark08="Log in with one tap"
mark09="Save your password now to make logging in even easier."
mark10="Enter email address or phone number"
mark11="Enter password"

# empty file for blank clipboard
touch /home/busyman/blank

# check if mobile facebook page is open
page_probe () {
for i in {1..20} ; do
	echo "page_probe..."
	zenity --info --title="page_probe" --text="page_probe..." --timeout 1
	xdotool search --sync --onlyvisible --name "$SPOT01" windowactivate
	xclip -selection clipboard /home/busyman/blank
	xdotool key --delay 200 Ctrl+a Ctrl+c Ctrl+Shift+a
	clip=$( xclip -out -selection clipboard )
		case "$clip" in
		*$mark10*)
			echo "Login page without password...''$mark10''"
			zenity --info --title="page_probe" --text="Login page without password...''$mark10''" --timeout $tol
			xdotool key --delay $kd Ctrl+f && xdotool type $mark10 && xdotool key --delay $kd Escape
			sleep 2
			xdotool key --delay $kd Ctrl+a Ctrl+c Ctrl+Shift+a
			clip=$( xclip -out -selection clipboard )
			if [ $clip = $empty01 ]
				then
				echo "This is empty clipboard, is it entry field? ..."
				zenity --info --title="Webpage content" --text="This is empty clipboard, is it entry field? ..." --timeout $to
				xdotool type --delay $kd $login
				xdotool key --delay $kd Ctrl+a Ctrl+c End
					clip=$( xclip -out -selection clipboard )
					if [ $clip = $login ]
					then
					xdotool key --delay $kd Return
					echo "Enter $login ..."
					zenity --info --title="Webpage content" --text="Enter $login ..." --timeout $to
					xdotool key --delay $kd Shift+Tab Ctrl+a Ctrl+c 
					clip2=$( xclip -out -selection clipboard )
						case "$clip2" in
						*mark11*)
						xdotool key --delay $kd Tab && xdotool type $password && xdotool key Return
						zenity --info --title="Enter..." --text="Password, Enter." --timeout $tol
							;;
						*)
						echo "Error, can not put password?..."
						;;	
						esac
					else
						echo "Error, is this entry field? ..."
						zenity --info --title="Webpage content" --text="Error, is this entry field? ..." --timeout $to
					fi
			fi
			/bin/bash /opt/busy4me/fb/fb-scroll &
			exit 0
		;;
		*$mark09*)
			echo "Logged successfuly... save-device page"
			zenity --info --title="page_probe" --text="Logged successfuly...save-device page" --timeout $tol
			xdotool key --delay $kd Ctrl+l && xdotool type --delay $kds $SPOT01url && xdotool key Return
			/bin/bash /opt/busy4me/fb/fb-scroll &
			exit 0
		;;
		*$mark08*)
			echo "Logged successfuly..."
			zenity --info --title="page_probe" --text="Logged successfuly..." --timeout $tol
			xdotool key --delay $kd Ctrl+l && xdotool type --delay $kds $SPOT01url && xdotool key Return
			/bin/bash /opt/busy4me/fb/fb-scroll &
			exit 0
		;;
		*$mark07*)
			echo "Logged successfuly..."
			zenity --info --title="page_probe" --text="Logged successfuly..." --timeout $to
			xdotool key --delay $kd Ctrl+l && xdotool type --delay $kds $SPOT01url && xdotool key Return
			/bin/bash /opt/busy4me/fb/fb-scroll &
			exit 0
		;;
		*$mark02*)
			echo "Login page OK..."
			zenity --info --title="page_probe" --text="Login page OK I see text \"$mark02\"... go to login..." --timeout $tos
			break
		;;
		*$mark03*)
			echo "Login page OK..."
			zenity --info --title="page_probe" --text="Login page OK I see text \"$mark03\"... go to login..." --timeout $tos
			break
		;;
		*)
			echo "probe again..."
			zenity --info --title="page_probe" --text="probe again..." --timeout $tos
		;;
		esac
	done
}
page_probe

# do login...
xdotool search --sync --onlyvisible --name "$SPOT01" windowactivate | logline

xclip -selection clipboard /home/busyman/blank
echo "entry_detect start"
entry01=0

entry_detect () {
xdotool key --delay $kd Ctrl+l Ctrl+a Ctrl+c
clip=$( xclip -out -selection clipboard )
if [ $clip = mark05 ]
then
	echo "This is mobile login page URL OK...  $mark05"
fi
while [ $entry01 -lt 2 ]
do
	xclip -selection clipboard /home/busyman/blank
	xdotool key --delay $kd Tab Ctrl+a Ctrl+c Ctrl+Shift+a
	clip=$( xclip -out -selection clipboard )
	
	case "$clip" in
		*$mark07*)
			echo "Logged successfuly... switch to fb.com"
			zenity --info --title="page_probe" --text="Logged successfuly... switch to fb.com ..." --timeout $tol
			xdotool key --delay $kd Ctrl+l
			xdotool type $SPOT01url
			xdotool key --delay $kd Return
			/bin/bash /opt/busy4me/fb/fb-scroll &
			exit 0
		;;
		*$mark04*)
		echo "The content with $mark04 .."
		zenity --info --title="Webpage content" --text="The content with $mark04 .. ..." --timeout $to
		;;
		*$mark05*)
		echo "This is URL entry bar with $mark05 address."
		zenity --info --title="Url entry bar" --text="This is URL entry bar with $mark05 address." --timeout $to
		;;
		$empty01)
		echo "This is empty clipboard, is it entry field? ..."
		zenity --info --title="Webpage content" --text="This is empty clipboard, is it entry field? ..." --timeout $to
		entry01=$((entry01+1))
		echo "entry01 = $entry01"
		#zenity --info --title="entry" --text="entry01 = $entry01" --timeout $to
		;;
		*)
		echo "This is something else ... what is it?"
		#zenity --info --title="Webpage content" --text="This is something else ... what is it?" --timeout $to
		;;
		
	esac
done
}
entry_detect
echo "This is End of $SCRIPT script"
zenity --info --title="End" --text="This is entry field... password?" --timeout $to
xdotool type --delay $kd $password
xdotool key --delay $kd Shift+Tab
xdotool type --delay $kd $login
xdotool key --delay $kd Tab Tab Ctrl+a Ctrl+c Ctrl+Shift+a Shift+Tab
clip=$( xclip -out -selection clipboard )

case "$clip" in
	*SHOW*)
	echo "Looks good? Enter?..."
	zenity --info --title="Ok" --text="Looks good? Enter?..." --timeout $tol
	xdotool key --delay $kd Return
	echo "... yes, Enter."
	zenity --info --title="Ok" --text="Yes, Enter." --timeout $tol
	;;
	*)
	echo "Something wrong? Can not see SHOW..."
	zenity --info --title="Ok" --text="Something wrong? Can not see SHOW..." --timeout $tol
	exit 0
	;;
esac

xdotool key --delay $kd Ctrl+l Ctrl+a
xdotool type --delay $kd $login_url
xdotool key --delay $kd Return
echo "Select URL bar and enter $login_url..."
zenity --info --title="Select URL bar" --text="Select URL bar and enter $login_url..." --timeout $tol
page_probe

echo "This is End of $SCRIPT script"
zenity --info --title="End" --text="This is End of $SCRIPT script" --timeout $to

