#!/bin/bash
SCRIPT=fb-write-my-groups
LOGFILE=/var/log/busy4me.log

xdotool mousemove 0 0

logline() {
    while IFS= read -r line; do
        echo "$(date +%F' '%T) $USER $SCRIPT - $line" | tee -a $LOGFILE 
    done
}

xdotool search --class zenity windowkill

kds=50 # Key Delay Short [miliseconds]
kd=200 # Key Delay [miliseconds]
kdl=500 # Key Delay Long [miliseconds]
tos=1 # Time Out Short zenity messages time out [seconds] 
to=2 # Time Out zenity messages time out [seconds] 
tol=5 # Time Out Long zenity messages time out [seconds] 

profile_id=""
profile_name="DariuszMarek1000000"

SPOT01="facebook" # spot 01
SPOT01url="https://facebook.com" # url 01
login=fblogin@mail.com
password=fbpassword
login_url=http://m.facebook.com
fb_groups_url="https://www.facebook.com/groups"

my_groups_url="$SPOT01url/$profile_name/groups"
about_url="$SPOT01url/$profile_name/about"
profile_url="$SPOT01url/$profile_name"

feh --bg-scale /home/busyman/wall_black_with_vertical_logo.jpg | logline

# go to my groups
xdotool search --onlyvisible --class chrome windowactivate
transset -a 1
xdotool key --delay $kdl Escape Ctrl+l && xdotool type --delay $kds $my_groups_url && xdotool key --delay $kdl Return
transset -a 0.7
(sleep 2 && wmctrl -F -a "page_probe" -b add,above) & zenity --info --title="page_probe" --text="Open $my_groups_url" --timeout 5
sleep 1
xdotool search --onlyvisible --class chrome windowactivate
mark01="Create Group"

my_groups_url_probe () {
for i in {1..20} ; do
	xdotool search --onlyvisible --class chrome windowactivate
	echo "my_groups_url_probe..." | logline
	xclip -selection clipboard /home/busyman/blank
	xdotool key --delay $kds Ctrl+a Ctrl+c Ctrl+Shift+a
	clip=$( xclip -out -selection clipboard )
		case "$clip" in
		*$mark01*)
		echo "I see groups..." | logline
		break
		;;
		*)
		echo "Can't see groups... try again..." | logline
		page_error=$((page_error+1))
		if [ $page_error -ge 19 ]; then
			echo "Page error, break script..." | logline
			exit 1
		fi
		;;
		esac
	done
}

my_groups_url_probe
(sleep 2 && wmctrl -F -a "write_my_groups" -b add,above) & zenity --info --title="write_my_groups" --text="Write my groups to local database..." --timeout 8 &
sleep 1
#zenity --info --title="Activate chrome" --text="search --onlyvisible --class chrome windowactivate" --timeout $to
xdotool search --onlyvisible --class chrome windowactivate
#my_groups_url_probe

mark02="More about you"
mark02_i=0
mark03="/groups/"
mark04="Leave Group"
mark05="#"
mark06="reviews"
mark07="reviews_written"

write_my_groups () {
iter=5
for (( i=1; i<$iter; i++ )); do
    echo "# Pick groups up... step $i"
    echo "$(( (i * 100) /$iter ))"
    sleep 0.5
    shift 1
done | zenity --progress --title="Pick groups up..." --percentage=0 --no-cancel --auto-close
echo "write_my_groups start..."
	echo "Search public...."
	xdotool search --onlyvisible --class chrome windowactivate
zenity --info --title="write_my_groups" --text="xdotool key --delay $kdl Tab Tab Tab" --timeout $to
	xdotool search --onlyvisible --class chrome windowactivate
	xdotool key --delay $kdl Tab Tab Tab
    sleep 0.5
zenity --info --title="write_my_groups" --text="xdotool key --delay $kdl Ctrl+f" --timeout $to
	xdotool search --onlyvisible --class chrome windowactivate
	xdotool key --delay $kdl Ctrl+f | logline
	xdotool type --delay $kdl "Public" | logline
    sleep 0.5
zenity --info --title="write_my_groups" --text="xdotool key --delay $kdl Escape" --timeout $to
	xdotool search --onlyvisible --class chrome windowactivate
	xdotool key --delay $kdl Escape | logline
	echo "Tab...."
    sleep 0.5
zenity --info --title="write_my_groups" --text="xdotool key --delay $kd Tab" --timeout $to
	xdotool search --onlyvisible --class chrome windowactivate
	xdotool key --delay $kd Tab
    sleep 0.5
	
mark06_i=0
#while (( mark06_i == 0 || not_valid_counter_1 < 10 || not_valid_counter_2 < 10 ))
while (( mark06_i == 0 ))
do
	xdotool search --onlyvisible --class chrome windowactivate
	xdotool key --delay $kd Escape Tab
	xdotool key --delay $kd Shift+F10
	xclip -selection clipboard /home/busyman/blank
	xdotool key --delay $kd e
	clip1=$( xclip -out -selection clipboard )
		case "$clip1" in
		*$mark05*)
#		zenity --info --title="clipboard" --text="This is not valid URL \n $clip1 \nNext..." --timeout $tos > /dev/null 2>&1
		not_valid_counter_1=$((not_valid_counter_1+1))
		if [ $not_valid_counter_1 -ge 10 ]; then
			echo "not valid group URL $not_valid_counter_1 times, break script..." | logline
			exit 1
		fi
		echo "Not valid url...not_valid_counter_1: $not_valid_counter_1"
		;;
		*$mark03*)
#		zenity --info --title="clipboard" --text="Group URL OK: \n $clip1" --timeout $tos > /dev/null 2>&1
		URL_counter=$((URL_counter+1))
		not_valid_counter_1=0
		not_valid_counter_2=0
		echo "URL_counter... $URL_counter"
		echo "$clip1" | logline
		;;
		*)
#		zenity --info --title="clipboard" --text="What is it?: \n $clip1" --timeout $tos > /dev/null 2>&1
		not_valid_counter_2=$((not_valid_counter_2+1))
		if [ $not_valid_counter_2 -ge 10 ]; then
			echo "not valid group URL $not_valid_counter_2 times, break script..." | logline
			break
		fi
		echo "This is not valid group URL... not_valid_counter_2: $not_valid_counter_2"
		;;
		*$mark06*)
#		zenity --info --title="clipboard" --text="This the end of Groups page... exit..." --timeout $tol > /dev/null 2>&1
		echo "This the end of Groups page... mark06 exit..." | logline
		mark06_i=1
		break
		;;
		*$mark07*)
#		zenity --info --title="clipboard" --text="This the end of Groups page... exit..." --timeout $tol > /dev/null 2>&1
		echo "This the end of Groups page... mark07 exit..." | logline
		mark06_i=1
		break
		;;
		esac
done
}

zenity --info --title="Function" --text="xdotool search --onlyvisible --class chrome windowactivate.... and Function write_my_groups" --timeout $to
xdotool search --onlyvisible --class chrome windowactivate --timeout $to
write_my_groups

(sleep 1 && wmctrl -F -a "URL_counter" -b add,above) & zenity --info --title="URL_counter" --text="Saved $URL_counter groups..."

scroll_to_end () {
echo "Start scrolling...."
xdotool search --onlyvisible --class chrome windowactivate
echo "Set trasparent... 0.7"
transset -a 0.7
echo "mark02 = $mark02"
echo "mark02_i = $mark02_i"

while [ $mark02_i -eq 0 ]
do
	echo "Scroll page down..." | logline
	xdotool key --delay $kds Page_Down
	xclip -selection clipboard /home/busyman/blank
	sleep 0.5
	xdotool key --delay $kds Ctrl+a Ctrl+c Ctrl+Shift+a
	clip=$( xclip -out -selection clipboard )
		case "$clip" in
		*$mark02*)
		echo "This is the end of page? I see $mark02"
			xdotool key --delay $kds Page_Down
			mark02_i=1
		;;
		*)
		echo "Scroll again...."
		;;
		esac
	echo "# Looking for end mark02......... "
done
}

#scroll_to_end

echo "$count01"

echo "Stop scrolling...."

transset -a 1
	
echo "fb-like-random-fanpages stop." | logline
	
